import { expect, test } from '@playwright/test'
import { TEST_PUZZLE } from '../fixtures/puzzle'

declare global {
  interface Window {
    __approachCanvas?: {
      approachEndpoint?: { x: number; y: number }
      ballCenter?: { x: number; y: number }
      lastLinePoint?: { x: number; y: number }
      lastArcCenter?: { x: number; y: number }
    }
  }
}

test('an archived approach ends with its trace attached to the stored ball', async ({ page }) => {
  await page.addInitScript(() => {
    localStorage.setItem('puttle:onboarding:v1', 'seen')
    const state = window.__approachCanvas = {}
    const prototype = CanvasRenderingContext2D.prototype
    const lineTo = prototype.lineTo
    const arc = prototype.arc
    const stroke = prototype.stroke
    const fill = prototype.fill

    prototype.lineTo = function (x, y) {
      state.lastLinePoint = { x, y }
      return lineTo.call(this, x, y)
    }
    prototype.arc = function (x, y, radius, startAngle, endAngle, counterclockwise) {
      state.lastArcCenter = { x, y }
      return arc.call(this, x, y, radius, startAngle, endAngle, counterclockwise)
    }
    prototype.stroke = function (...args) {
      if (String(this.strokeStyle) === 'rgba(174, 201, 183, 0.72)') {
        state.approachEndpoint = state.lastLinePoint
      }
      return Reflect.apply(stroke, this, args)
    }
    prototype.fill = function (...args) {
      if (String(this.fillStyle) === '#fffef5') {
        state.ballCenter = state.lastArcCenter
      }
      return Reflect.apply(fill, this, args)
    }
  })

  await page.route('**/puzzles/2026-01-01.json', (route) => route.fulfill({
    json: {
      ...TEST_PUZZLE,
      // Recreate an archived puzzle generated by an older simulator.
      ball: { x: TEST_PUZZLE.ball.x + 1, y: TEST_PUZZLE.ball.y },
    },
  }))
  await page.goto('/?archive=2026-01-01')

  await expect(page.getByRole('button', { name: 'Putt', exact: true })).toBeEnabled({ timeout: 10_000 })
  await page.locator('.green-canvas').evaluate(() => new Promise<void>((resolve) => {
    requestAnimationFrame(() => requestAnimationFrame(() => resolve()))
  }))

  const centers = await page.evaluate(() => window.__approachCanvas)
  expect(centers?.approachEndpoint).toBeDefined()
  expect(centers?.ballCenter).toBeDefined()
  expect(Math.hypot(
    (centers?.approachEndpoint?.x ?? 0) - (centers?.ballCenter?.x ?? 0),
    (centers?.approachEndpoint?.y ?? 0) - (centers?.ballCenter?.y ?? 0),
  )).toBeLessThan(0.01)
})
